# Generated by Django 4.2.4 on 2023-08-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane_name', models.CharField(max_length=60)),
                ('departure', models.CharField(max_length=60)),
                ('destination', models.CharField(max_length=60)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('additionalInformation', models.CharField(max_length=120)),
            ],
        ),
    ]
