# Generated by Django 4.2.4 on 2023-09-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_rename_additionalinformation_flight_additional_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShortcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('url', models.URLField(max_length=255)),
                ('valid_to', models.DateTimeField()),
            ],
        ),
    ]
